chpater 04 예제 + (test containers + mariadb + jpa) 직접 해보기 + codeowners
IT-BOOK-CLUB/study-2409-cloud-native-spring-in-action pull request #3
Opened 2024-09-21 05:28 UTC by namyoungjun96

2024-09-21 06:44 UTC, mintheon requested changes
확인해보니 checks에서도 에러가 발생하네요~
에러 내용은 테스트코드가 실패했다는 에러인데 확인하시고 해결 부탁드려요~

2024-09-21 06:44 UTC, mintheon commented on .github/CODEOWNERS
> +* @21lva, @Rat2Race, @goeom77, @JunseongHeo, @namyoungjun96, @devkunst, @hwan33
```suggestion
* @21lva @Rat2Race @goeom77 @JunseongHeo @namyoungjun96 @devkunst @hwan33
```

2024-09-28 11:58 UTC, devkunst approved these changes
이거 들어갈 수 있나요? 들어갈 수 있으면 머지해주셔요~

2024-09-28 12:52 UTC, mintheon approved these changes

2024-09-28 12:52 UTC, merged